# Generated by Django 4.2.3 on 2023-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaservices', '0002_rename_full_name_customer_name_remove_payment_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
